name: 'Run vimlint with reviewdog'
description: '🐶 Run vimlint with reviewdog on pull requests to improve code review experience.'
author: 'Tsuyoshi CHO <Tsuyoshi.CHO+develop@Gmail.com>'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-check,github-pr-review].
      Default is github-pr-review.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_level:
    description: |
      Optional.  Exit code control for reviewdog, [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: |
      Deprecated.

      Optional.  Exit code for reviewdog when errors are found [true,false]
      Default is `false`.

      If `true` is set, it will be interpreted as "-fail-level=error".
      But if "-fail-level" is set non-`none`, it will be ignored.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  target:
    description: 'vimlint test target directory'
    default: 'autoload'
  vimlint_flags:
    description: "flags and args of vimlint command. Default: '-e EVL102.l:_=1 -c func_abort=1'"
    required: true
    default: '-e EVL102.l:_=1 -c func_abort=1'
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'vimlint'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'alert-octagon'
  color: 'blue'
